
name: Node.js Package

on:
  push:
    branches: [ dev ]
    workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

        with:
          node-version: 16
          registry-url: http://registry.npmjs.org/
      - run: npm ci
      - run: npm run test:prod
      - run: npm run build:prod

